<?php

/**
 * @file
 * Creates a token which gives email to friend functionality on a desired page.
 */

use Drupal\Core\Routing\RouteMatchInterface;

module_load_include('inc', 'email_token', 'email_token.tokens');

/**
 * Implements hook_help().
 */
function email_token_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.email_token':
      $output = t('<p>This module provides <b>3 tokens.</b></p>
                <p>(a) <b>[etf:gin-title]</b> gives current node title. (blank for front page)</p>
                <p>(b) <b>[etf:gin-url]</b> gives current node url.</p>
                <p>(c) <b>[etf:gin-email]</b> provides an email link. A link will get generated "mail me" embeded in a div with class <b>"gin-email-token"</b>.
                <ul>
                <li>You can put image icon on this class by using css.</li>
                <li>This token will open outlook page</li>
                <li>Body should have the link of the page, the subject should be by default browser title</li>
                </ul>
                </p>

                <h2> To use these tokens: </h2>
                
                <p> This module adds a filter <strong>"Email Token Filter"</strong>. you can enable this filter at <strong> "admin/config/content/formats" </strong>. </p>
                
                <b> Steps to enable token filter </b>
                <ul><li>At path "admin/config/content/formats", there is a list of text formats like Basic Html, Restricted Html, Full Html, etc. </li>
                <li>Click on "Configure" button of any text-format say(Basic HTML). You will see a list of Enabled filters. </li>
                <li>Enable checkbox for "Email Token Filter". </li>
                <li>Save configuration.</li>
                </ul>
                
                <p>You have successfully added token filter to your existing text format. </p>
                
                Now, You can place these tokens in your blocks, nodes or at the places where you can see a list of text-formats.
                Add token and select "Basic HTML".
                Hit save.
                Thats it.

                
                ');
      
    return $output;
    default:
    }
}